# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLfM2UpOxCms9Phdbf-FMU_8T9jYuFdm
"""

pip install pandas

import pandas as pd
import datetime

# Sample log data
log_data = [
    {"timestamp": "2025-01-30 10:00:00", "source_ip": "192.168.1.1", "event_type": "login_success", "user": "admin"},
    {"timestamp": "2025-01-30 10:05:00", "source_ip": "192.168.1.2", "event_type": "login_failure", "user": "admin"},
    {"timestamp": "2025-01-30 10:10:00", "source_ip": "192.168.1.3", "event_type": "port_scan", "user": "N/A"},
    {"timestamp": "2025-01-30 10:15:00", "source_ip": "192.168.1.2", "event_type": "login_failure", "user": "admin"},
    {"timestamp": "2025-01-30 10:20:00", "source_ip": "192.168.1.2", "event_type": "login_failure", "user": "admin"},
]

# Load log data into a DataFrame
df = pd.DataFrame(log_data)

# Convert timestamp to datetime for easier analysis
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Define a simple threat detection rule
def detect_brute_force(df):
    """Detect multiple failed login attempts from the same IP within 10 minutes."""
    brute_force_alerts = []

    grouped = df[df["event_type"] == "login_failure"].groupby("source_ip")

    for source_ip, group in grouped:
        group = group.sort_values("timestamp")
        time_diff = group["timestamp"].diff().dt.total_seconds()

        # Check if there are 3 failures within 10 minutes
        if len(group) >= 3 and time_diff.dropna().sum() <= 600:
            brute_force_alerts.append(f"Brute force attack detected from IP {source_ip}")

    return brute_force_alerts

def detect_port_scanning(df):
    """Detect port scanning events."""
    port_scan_events = df[df["event_type"] == "port_scan"]
    alerts = [f"Port scanning detected from IP {row['source_ip']}" for _, row in port_scan_events.iterrows()]
    return alerts

# Analyze logs for threats
alerts = detect_brute_force(df) + detect_port_scanning(df)

# Print threat detection alerts
if alerts:
    print("Threat Detection Alerts:")
    for alert in alerts:
        print(f"  - {alert}")
else:
    print("No threats detected.")